[package]
name = "cool-sys"
version = "0.1.0"
edition = "2021"

links="cool"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
cc = "1.0.104" # Require at least this version for fixes for WASI build.
